### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Jisoo-Lee93** [Standard-Library-Maker/STL-anyone#12]
1. Priority Queue - complete
2. Heap - complete
3. HashMap - complete
4. Heap 
 1) 강세응 메일주소
 2) pushMax/pushMax : 인자가 비어있는경우 예외처리 확인
 3) 전체적인 함수 예제 및 출력값 확인
5. Binary Tree
 1) isEmpty() 어디있는지 확인
 2) push,/postOrder/inOrder/preOrder : 인자가 비어있는경우 예외처리 확인
 3) 테스트과정에서 var bt = new BinaryTree (); bt.push(1); bt.push(2); bt.push(3); bt.postOrder(this.root); 하니 에러나는거 확인 (inOrder, preOrder도 마찬가지로 에러발생함)
6. Binary Search Tree
 1) isEmpty() 어디있는지 확인
 2) insert/inOrder/minValue/maxValue/find/delete : 인자가 비어있는 경우 예외처리 확인
 3) 테스트과정에서 var bst = new BinarySearchTree (); bst.insert(1); bst.insert(2); bst.insert(3); bst.state();
이게 안돌아가는데 이유확인좀..
7. ArrQueue
 1) push :  인자가 비어있는 경우 예외 처리
 2) pop : 리턴할때 없을때 예외처리
 3) front, end : 비어있는 경우 예외 처리
8. CircularQueue
 1) push : 인자가 비어있는경우 예외처리
 2) pop : 리턴할때 없을때 예외처리
 3) front, end : 비어있는 경우 예외 처리
9. Stack
 1) push :  인자가 비어있는 경우 예외 처리
 2) pop : 리턴할때 없을때 예외처리
 3) top : 비어있는 경우 예외 처리
10. linked list - complete
11. double linked list - complete
12. list, bubble sort는 나중에하겠음

**Comment by seeungKang** [comment]
4. Heap

**Comment by seeungKang** [comment]
4. Heap
   1. 메일 주소 업데이트
   2. 예외 처리 완료
   3. 에러 확인
5. Binary Tree
   1. isEmpty 추가
   2. 예외 처리 완료
   3. 에러 확인
6. Binary Search Tree
   1. isEmpty 추가
   2. 예외 처리 완료
   3. 에러 확인

**Comment by zerone2** [comment]
1. Queue 주석 변경 (누락된 부분 추가)
2. CircularQueue 주석 변경 (잘못된 부분 수정)
