### ISSUE TITLE
Priority queue pop function

### ISSUE THREAD

**Issue by zerone2** [Standard-Library-Maker/STL-anyone#20]
pq pop 함수 리턴값 필요함.
어떤 값이 pop 되었는지 리턴해줘야함.

지수님 부탁함. 
queue나 stack처럼 값만 return 해주면 됨.

**Comment by Jisoo-Lee93** [comment]
기존 c++ priority queue :: pop() 사용법을 참고하면 최우선순위 값은 삭제하되, 삭제된 값은 리턴하지 않는 것으로 명시되어 있음.
기존 stl과 같은 방식으로 리턴하지 않도록 구현하는 것도 괜찮을거 같은데 어떠신지..?

**Comment by zerone2** [comment]
사용자 입장에서 뭐가 삭제됐는지 팝업메시지로 한번더 알려주고 싶어서 리턴이 있으면 좋겠어요
테스트 쪽은 상관없는데 web 쪽은 만들어주세요

**Comment by Jisoo-Lee93** [comment]
그럼 web구현할때 참고해서 팝업으로 띄우겠습니다

**Comment by zerone2** [comment]
제가 대충 구현해놔서 풀 땡기고 확인해보시길 바랍니다.
lib쪽에 priorityqueue.js 에서 pop 함수 리턴값만 넣어주면 pop버튼 눌렀을 때
값 뜰거에요. 지금은 undefined로 뜹니다.

**Comment by Jisoo-Lee93** [comment]
추가하였슴다
