### ISSUE TITLE
현재 진행상황(~2/21)

### ISSUE THREAD

**Issue by Jisoo-Lee93** [Standard-Library-Maker/STL-anyone#23]
**Priority Queue**  
_- Tree형식의 구조라서 output을 stack, queue와 다르게 구현해야 하는데, 
  구현과정에서 어려움이 많아서  함수 작동 먼저 구현해두었고, output부분은 일단 보류했음_
1. Start : greater, less 옵션을 라디오버튼으로 구현하여 옵션 선택후 시작하도록 구현
2. isEmpty
3. Size
4. Top
5. Push
6. pop
7. state

**Deque**
 _- Queue/stack이 전부 들어있는 자료구조 형식이라 push 및 pop을 앞뒤로 적용시켜야 하기 때문에
   output부분은 보류_
1. push_front
2. push_Back
3. pop_front
4. pop_back
5. front
6. back
7. begin : iterator를 출력하는 함수인데, front함수와 어느정도 겹쳐서 생략해도 될거같음
8. end :: iterator를 출력하는 함수인데, back함수와 어느정도 겹쳐서 생략해도 될거같음
9. isEmpty
10. size
11.  at : index버그 있는듯 수정중**
12. erase  : index버그 있는듯 수정중**
13. clear  :  index버그 있는듯 수정중**
14. state

**HashMap**
_- (key, value)값을 넣기 때문에 start 이후에 hashmap에 put한 값들은 result창에 보이도록 해둠_
1. put
2. containskey :  Set형식을 리턴받아서 보여줘서 가독성이 좀 떨어짐 (추가적으로 수정하는게 좋을듯)
3. containsValue : Set형식을 리턴받아서 보여줘서 가독성이 좀 떨어짐 (추가적으로 수정하는게 좋을듯)
4. get
5. keySet
6. EntrySet
7. remove
8. clear
9. isEmpty
10. size
11. state

**Comment by Jisoo-Lee93** [comment]
priorityQueue, Deque : output 보여주는 textarea 에 실시간으로 값 받아와서 뿌려주도록 변경함 (적용완료)

**Comment by zerone2** [comment]
훌륭!

**Comment by seeungKang** [comment]
alba full time이 끝나는대로 jisoo-Lee93 code 참고하여 수정하겠음

**Comment by Jisoo-Lee93** [comment]
at erase clear : 버그 수정
